title: Vincents 342 Website
author: CyberVA
email: vallen813@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  My website I'm using for 342!!

# social links
github_username:  CyberVA # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
